//Defines German messages v0.5

#define ATTXTCHANNEL "Kanal"
#define ATTXTCHANNELS "Kanäle"
#define ATTXTDEVICE "Gerät"
#define ATTXTDEVICES "Geräte"
#define ATTXTBACK "Zurück"
#define ATTXTSAVE "Speichern"
#define ATTXTDELETE "Löschen"
#define ATTXTDETAILS "Details"
#define ATTXTDEVSTP "Geräte Setup"
#define ATTXTWDGSTP "Widget Setup"
#define ATTXTSYSSTP "System Setup"
#define ATTXTWIDGET "Widget"
#define ATTXTSMARTHOME "Smart Home"
#define ATTXTCANCEL "Abbruch"
#define ATTXTNAME "Name"
#define ATTXTEXTRA "Extra"
#define ATTXTWDSMALL "klein"
#define ATTXTWDLEFT "links"
#define ATTXTWDRIGHT "rechts"
#define ATTXTWDBIG   "groß"
#define ATTXTDONE "Fertig"
#define ATTXTBACKGROUND "Hintergrund"
#define ATTXTBGON "Hintergrd. ein"
#define ATTXTFONT "Schrift"
#define ATTXTSIZE "Größe"
#define ATTXTLABEL "Bezeichnung"
#define ATTXTDECIMALS "Dezimalstellen"
#define ATTXTPAGE "Seite"
#define ATTXTPOSAITION "Position"
#define ATTXTWLAN "WLAN"
#define ATTXTWPS "WPS"
#define ATTXTPASSWORD "Passwort"
#define ATTXTNETWORK "Netzwerk"
#define ATTXTNOWLAN "Kein WLAN gefunden"
#define ATTXTACTIVE "aktiv"
#define ATTXTNTPSERVER "NTP Server"
#define ATTXTPAGE "Seite"
#define ATTXTON "Ein"
#define ATTXTOFF "Aus"
#define ATTXTINTERVAL "Refresh (s)"
