//Defines German messages v0.1

#define ATTXTCHANNEL "Kanal"
#define ATTXTCHANNELS "Kanäle"
#define ATTXTDEVICE "Gerät"
#define ATTXTDEVICES "Geräte"
#define ATTXTBACK "Zurück"
#define ATTXTSAVE "Speichern"
#define ATTXTDELETE "Löschen"
#define ATTXTDETAILS "Details"
#define ATTXTDEVSTP "Geräte Setup"
#define ATTXTWDGSTP "Widget Setup"
#define ATTXTWIDGET "Widget"
#define ATTXTSMARTHOME "Smart Home"
#define ATTXTCANCEL "Abbruch"
#define ATTXTNAME "Name"
#define ATTXTEXTRA "Extra"
#define ATTXTWDSMALL "klein"
#define ATTXTWDLEFT "links"
#define ATTXTWDRIGHT "rechts"
#define ATTXTWDBIG   "groß"
#define ATTXTDONE "Fertig"
#define ATTXTBACKGROUND "Hintergrund"
#define ATTXTBGON "Hintergrd. ein"
#define ATTXTFONT "Schrift"
#define ATTXTSIZE "Größe"
#define ATTXTLABEL "Bezeichnung"
#define ATTXTDECIMALS "Dezimalstellen"
#define ATTXTPAGE "Seite"
#define ATTXTPOSAITION "Position"
