//Defines English messages v0.5

#define ATTXTCHANNEL "Channel"
#define ATTXTCHANNELS "Channels"
#define ATTXTDEVICE "Device"
#define ATTXTDEVICES "Devices"
#define ATTXTBACK "Back"
#define ATTXTSAVE "Save"
#define ATTXTDELETE "Delete"
#define ATTXTDETAILS "Details"
#define ATTXTDEVSTP "Device Setup"
#define ATTXTWDGSTP "Widget Setup"
#define ATTXTSYSSTP "System Setup"
#define ATTXTWIDGET "Widget"
#define ATTXTSMARTHOME "Smart Home"
#define ATTXTCANCEL "Cancel"
#define ATTXTNAME "Name"
#define ATTXTEXTRA "Extra"
#define ATTXTWDSMALL "small"
#define ATTXTWDLEFT "left"
#define ATTXTWDRIGHT "right"
#define ATTXTWDBIG   "big"
#define ATTXTDONE "Done"
#define ATTXTBACKGROUND "Background"
#define ATTXTBGON "Backgrd. On"
#define ATTXTFONT "Font"
#define ATTXTSIZE "Size"
#define ATTXTLABEL "Label"
#define ATTXTDECIMALS "Decimals"
#define ATTXTPAGE "Page"
#define ATTXTPOSAITION "Position"
#define ATTXTWLAN "WLAN"
#define ATTXTWPS "WPS"
#define ATTXTPASSWORD "Password"
#define ATTXTNETWORK "Network"
#define ATTXTNOWLAN "No WLAN found"
#define ATTXTACTIVE "active"
#define ATTXTNTPSERVER "NTP server"
#define ATTXTPAGE "Page"
#define ATTXTON "On"
#define ATTXTOFF "Off"
#define ATTXTINTERVAL "Refresh (s)"
